version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gdpr_db
      POSTGRES_USER: gdpr_user
      POSTGRES_PASSWORD: replace_me
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gdpr_db
      SPRING_DATASOURCE_USERNAME: gdpr_user
      SPRING_DATASOURCE_PASSWORD: replace_me
      JWT_SECRET: ChangeThisJWTSecretInProduction
    ports:
      - '8080:8080'
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - app

volumes:
  pgdata:
